### ISSUE TITLE
Permanently loading mercy system

### ISSUE THREAD

**Issue by Feederstyx** [dnchattan/raid-toolkit-public#22]

**Comment by martindunsmore** [comment]
I'm also having the same issue.

**Comment by dnchattan** [comment]
@Feederstyx @martindunsmore can either of you share your client logs?  They are located at `%userprofile%\appdata\local\raid-toolkit\app-1.3.1\logs`. The two most recent files should be enough.

**Comment by martindunsmore** [comment]
Sure, log attached as requested.

[log_4500_2021.04.23T08.33.56.747Z.log](https://github.com/dnchattan/raid-toolkit-public/files/6364682/log_4500_2021.04.23T08.33.56.747Z.log)

**Comment by dnchattan** [comment]
ugh. looks like the error details aren't getting logged correctly. will include better logging in the next update, if you don't mind sending logs again when the app updates?

**Comment by martindunsmore** [comment]
> ugh. looks like the error details aren't getting logged correctly. will include better logging in the next update, if you don't mind sending logs again when the app updates?

Yeah no problem at all.

**Comment by martindunsmore** [comment]
> ugh. looks like the error details aren't getting logged correctly. will include better logging in the next update, if you don't mind sending logs again when the app updates?

Here's logs from version 1.3.2

[log_17416_2021.04.23T16.27.07.125Z.log](https://github.com/dnchattan/raid-toolkit-public/files/6366775/log_17416_2021.04.23T16.27.07.125Z.log)
[log_11836_2021.04.23T16.27.08.588Z.log](https://github.com/dnchattan/raid-toolkit-public/files/6366776/log_11836_2021.04.23T16.27.08.588Z.log)
[log_9080_2021.04.23T16.27.08.393Z.log](https://github.com/dnchattan/raid-toolkit-public/files/6366777/log_9080_2021.04.23T16.27.08.393Z.log)

**Comment by dnchattan** [comment]
@martindunsmore any chance that you haven't ever pulled a sacred shard?

**Comment by Feederstyx** [comment]
that's true for me

**Comment by martindunsmore** [comment]
> @martindunsmore any chance that you haven't ever pulled a sacred shard?

I don't think I have pulled a sacred shard before.

**Comment by dnchattan** [comment]
Perfect, thanks for confirming. Should be able to fix in the next update 😄

**Comment by dnchattan** [comment]
Will be included in 1.3.3 release!

**Comment by martindunsmore** [comment]
> Will be included in 1.3.3 release!

Perfect, works now! :)
