### ISSUE TITLE
Images are not loading

### ISSUE THREAD

**Issue by Sbierbaum** [dnchattan/raid-toolkit-public#23]
Shards and Heroes images are not loading, show broken image icon.
Is there a way i can throubleshoot this to help you find the cause of this ?

**Comment by dnchattan** [comment]
@Sbierbaum can you grab your client logs and share them? They are located at `%userprofile%\appdata\local\raid-toolkit\app-1.3.1\logs`.  The two most recent files should be enough.

**Comment by Sbierbaum** [comment]
[log_1048_2021.04.23T08.09.48.361Z.log](https://github.com/dnchattan/raid-toolkit-public/files/6364402/log_1048_2021.04.23T08.09.48.361Z.log)
[log_1968_2021.04.23T07.47.15.282Z.log](https://github.com/dnchattan/raid-toolkit-public/files/6364403/log_1968_2021.04.23T07.47.15.282Z.log)

**Comment by dnchattan** [comment]
@Sbierbaum perfect. thanks! Looks like some error reading something from the registry, might be that the registry path is different for plarium play when installed in French?

**Comment by Sbierbaum** [comment]
Got it to work !
You need to launch as administrator both plarium play and raid-toolkit and everything works fine.

Thanks for your help and your work 👍
