### ISSUE TITLE
 installation issue

### ISSUE THREAD

**Issue by MP-147** [dnchattan/raid-toolkit-public#26]
I get the following errors during installation:
 Uncaught Exception:
 Error: EPERM: operation not permitted, mkdir 'C:\Windows\system32\logs'  ...
I have no write permission to this directory.
Can you modify this in the next update ?

**Comment by dnchattan** [comment]
I'll take a look, thanks for the report!

**Comment by dnchattan** [comment]
I suspect this is what's causing some AV apps to go nuts as well.. hopefully this will hit two birds with one stone.

**Comment by dnchattan** [comment]
@MP-147 please try latest 1.3.2 release here: https://github.com/dnchattan/raid-toolkit-public/releases/tag/v1.3.2 

If you still have any issues with installation, please re-open and I'll take another look.

**Comment by MP-147** [comment]
thank you for the quick response . :-)
I am now one step further.
but 1.3.2 unfortunately does not run with me, I only get a blue window.
See attached logs 

[log_3024_2021.04.24T08.43.30.287Z.log](https://github.com/dnchattan/raid-toolkit-public/files/6369152/log_3024_2021.04.24T08.43.30.287Z.log)
[log_7432_2021.04.24T08.43.32.859Z.log](https://github.com/dnchattan/raid-toolkit-public/files/6369153/log_7432_2021.04.24T08.43.32.859Z.log)
[log_9312_2021.04.24T08.43.32.819Z.log](https://github.com/dnchattan/raid-toolkit-public/files/6369154/log_9312_2021.04.24T08.43.32.819Z.log)

**Comment by dnchattan** [comment]
are you still having an issue with the latest? Is the blue window the splash screen, or is it the full app window (with a titlebar)? If the latter, try resizing or dragging the window- I've occasionally seen it not paint right away, might be a bug in electron.

**Comment by dnchattan** [comment]
closing stale issues, reopen if you have any issues with the latest version

**Comment by MP-147** [comment]
Hi,yes, nothing has changed, I see after program start only the blue window, it can not be changed

Best regards MP-147    Am Donnerstag, 13. Mai 2021, 23:49:00 MESZ hat dnchattan ***@***.***> Folgendes geschrieben:  
 
 


Closed #26.
