### ISSUE TITLE
Install error: Game version not supported

### ISSUE THREAD

**Issue by Raizer25** [dnchattan/raid-toolkit-public#40]
I get this error when trying to install (pops after choosing yes to auto update then continuing):
GAME VERSION IS NOT SUPPORTED, AN UPDATE TO RAID TOOLKIT IS REQUIRED. RAID VERSION: '239' APP VERSION: '238'

I click for Check for Updates and it goes back to the error, then Retry does nothing. 

![Capture1](https://user-images.githubusercontent.com/84149559/118167534-a5743c00-b3db-11eb-8de0-be1aff37d1d8.PNG)

**Comment by dnchattan** [comment]
New version will be out soon. Gotta update it for their latest game update.

**Comment by Raizer25** [comment]
OK great, do you have an eta?

**Comment by dnchattan** [comment]
it's out now, auto update should appear on restart in ~15 min

**Comment by Raizer25** [comment]
Awesome thanks!
